
package wsjuros;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JurosWS", targetNamespace = "http://juros.ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JurosWS {


    /**
     * 
     * @param taxa
     * @param capital
     * @param periodo
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "juroSimples", targetNamespace = "http://juros.ws/", className = "wsjuros.JuroSimples")
    @ResponseWrapper(localName = "juroSimplesResponse", targetNamespace = "http://juros.ws/", className = "wsjuros.JuroSimplesResponse")
    @Action(input = "http://juros.ws/JurosWS/juroSimplesRequest", output = "http://juros.ws/JurosWS/juroSimplesResponse")
    public float juroSimples(
        @WebParam(name = "capital", targetNamespace = "")
        float capital,
        @WebParam(name = "taxa", targetNamespace = "")
        float taxa,
        @WebParam(name = "periodo", targetNamespace = "")
        int periodo);

    /**
     * 
     * @param taxa
     * @param capital
     * @param periodo
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "juroComposto", targetNamespace = "http://juros.ws/", className = "wsjuros.JuroComposto")
    @ResponseWrapper(localName = "juroCompostoResponse", targetNamespace = "http://juros.ws/", className = "wsjuros.JuroCompostoResponse")
    @Action(input = "http://juros.ws/JurosWS/juroCompostoRequest", output = "http://juros.ws/JurosWS/juroCompostoResponse")
    public float juroComposto(
        @WebParam(name = "capital", targetNamespace = "")
        float capital,
        @WebParam(name = "taxa", targetNamespace = "")
        float taxa,
        @WebParam(name = "periodo", targetNamespace = "")
        int periodo);

    /**
     * 
     * @param taxa
     * @param capital
     * @param periodo
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "montanteJuroComposto", targetNamespace = "http://juros.ws/", className = "wsjuros.MontanteJuroComposto")
    @ResponseWrapper(localName = "montanteJuroCompostoResponse", targetNamespace = "http://juros.ws/", className = "wsjuros.MontanteJuroCompostoResponse")
    @Action(input = "http://juros.ws/JurosWS/montanteJuroCompostoRequest", output = "http://juros.ws/JurosWS/montanteJuroCompostoResponse")
    public float montanteJuroComposto(
        @WebParam(name = "capital", targetNamespace = "")
        float capital,
        @WebParam(name = "taxa", targetNamespace = "")
        float taxa,
        @WebParam(name = "periodo", targetNamespace = "")
        int periodo);

    /**
     * 
     * @param taxa
     * @param capital
     * @param periodo
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "montanteJuroSimples", targetNamespace = "http://juros.ws/", className = "wsjuros.MontanteJuroSimples")
    @ResponseWrapper(localName = "montanteJuroSimplesResponse", targetNamespace = "http://juros.ws/", className = "wsjuros.MontanteJuroSimplesResponse")
    @Action(input = "http://juros.ws/JurosWS/montanteJuroSimplesRequest", output = "http://juros.ws/JurosWS/montanteJuroSimplesResponse")
    public float montanteJuroSimples(
        @WebParam(name = "capital", targetNamespace = "")
        float capital,
        @WebParam(name = "taxa", targetNamespace = "")
        float taxa,
        @WebParam(name = "periodo", targetNamespace = "")
        int periodo);

}
