
package ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSJuros", targetNamespace = "http://service.juros.soap.ws.gus/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSJuros {


    /**
     * 
     * @param taxa
     * @param capital
     * @param periodo
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "montanteJuroComposto", targetNamespace = "http://service.juros.soap.ws.gus/", className = "ws.MontanteJuroComposto")
    @ResponseWrapper(localName = "montanteJuroCompostoResponse", targetNamespace = "http://service.juros.soap.ws.gus/", className = "ws.MontanteJuroCompostoResponse")
    @Action(input = "http://service.juros.soap.ws.gus/WSJuros/montanteJuroCompostoRequest", output = "http://service.juros.soap.ws.gus/WSJuros/montanteJuroCompostoResponse")
    public float montanteJuroComposto(
        @WebParam(name = "capital", targetNamespace = "")
        float capital,
        @WebParam(name = "taxa", targetNamespace = "")
        float taxa,
        @WebParam(name = "periodo", targetNamespace = "")
        int periodo);

    /**
     * 
     * @param taxa
     * @param capital
     * @param periodo
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "montanteJuroSimples", targetNamespace = "http://service.juros.soap.ws.gus/", className = "ws.MontanteJuroSimples")
    @ResponseWrapper(localName = "montanteJuroSimplesResponse", targetNamespace = "http://service.juros.soap.ws.gus/", className = "ws.MontanteJuroSimplesResponse")
    @Action(input = "http://service.juros.soap.ws.gus/WSJuros/montanteJuroSimplesRequest", output = "http://service.juros.soap.ws.gus/WSJuros/montanteJuroSimplesResponse")
    public float montanteJuroSimples(
        @WebParam(name = "capital", targetNamespace = "")
        float capital,
        @WebParam(name = "taxa", targetNamespace = "")
        float taxa,
        @WebParam(name = "periodo", targetNamespace = "")
        int periodo);

    /**
     * 
     * @param taxa
     * @param capital
     * @param periodo
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "juroComposto", targetNamespace = "http://service.juros.soap.ws.gus/", className = "ws.JuroComposto")
    @ResponseWrapper(localName = "juroCompostoResponse", targetNamespace = "http://service.juros.soap.ws.gus/", className = "ws.JuroCompostoResponse")
    @Action(input = "http://service.juros.soap.ws.gus/WSJuros/juroCompostoRequest", output = "http://service.juros.soap.ws.gus/WSJuros/juroCompostoResponse")
    public float juroComposto(
        @WebParam(name = "capital", targetNamespace = "")
        float capital,
        @WebParam(name = "taxa", targetNamespace = "")
        float taxa,
        @WebParam(name = "periodo", targetNamespace = "")
        int periodo);

    /**
     * 
     * @param taxa
     * @param capital
     * @param periodo
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "juroSimples", targetNamespace = "http://service.juros.soap.ws.gus/", className = "ws.JuroSimples")
    @ResponseWrapper(localName = "juroSimplesResponse", targetNamespace = "http://service.juros.soap.ws.gus/", className = "ws.JuroSimplesResponse")
    @Action(input = "http://service.juros.soap.ws.gus/WSJuros/juroSimplesRequest", output = "http://service.juros.soap.ws.gus/WSJuros/juroSimplesResponse")
    public float juroSimples(
        @WebParam(name = "capital", targetNamespace = "")
        float capital,
        @WebParam(name = "taxa", targetNamespace = "")
        float taxa,
        @WebParam(name = "periodo", targetNamespace = "")
        int periodo);

}
