
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSJuros", targetNamespace = "http://service.juros.soap.ws.gus/", wsdlLocation = "http://ws-soap-juros.gustavo-lara.codes/juros?wsdl")
public class WSJuros_Service
    extends Service
{

    private final static URL WSJUROS_WSDL_LOCATION;
    private final static WebServiceException WSJUROS_EXCEPTION;
    private final static QName WSJUROS_QNAME = new QName("http://service.juros.soap.ws.gus/", "WSJuros");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ws-soap-juros.gustavo-lara.codes/juros?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSJUROS_WSDL_LOCATION = url;
        WSJUROS_EXCEPTION = e;
    }

    public WSJuros_Service() {
        super(__getWsdlLocation(), WSJUROS_QNAME);
    }

    public WSJuros_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSJUROS_QNAME, features);
    }

    public WSJuros_Service(URL wsdlLocation) {
        super(wsdlLocation, WSJUROS_QNAME);
    }

    public WSJuros_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSJUROS_QNAME, features);
    }

    public WSJuros_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSJuros_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSJuros
     */
    @WebEndpoint(name = "WSJurosPort")
    public WSJuros getWSJurosPort() {
        return super.getPort(new QName("http://service.juros.soap.ws.gus/", "WSJurosPort"), WSJuros.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSJuros
     */
    @WebEndpoint(name = "WSJurosPort")
    public WSJuros getWSJurosPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.juros.soap.ws.gus/", "WSJurosPort"), WSJuros.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSJUROS_EXCEPTION!= null) {
            throw WSJUROS_EXCEPTION;
        }
        return WSJUROS_WSDL_LOCATION;
    }

}
